<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Services\RelationshipService;

/**
 * @var Individual $individual
 * @var Family     $family
 * @var string     $title
 * @var boolean    $with_uid
 * @var boolean    $with_css
 * @var boolean    $with_link_symbol
 * @var string     $link_symbol
 */

?>

<table class="table table-sm wt-facts-table wt-family-navigator-family mitalteli-show-xref-table">
    <caption class="text-center wt-family-navigator-family-heading">
        <?php if (empty($family)) : ?>
            <!-- the individual itself -->
            <?= $title ?>
        <?php else : ?>
            <?php if ($family->canShow()) : ?>
                <?= $title ?><?php if ($with_link_symbol) : ?> <a href="<?= e($family->url()) ?>"><?= e($link_symbol ?? '⮺') ?></a><?php endif ?>
                <p class='uid'>(<?= $family->xref() ?><?php if ($with_uid) : ?> - <?= $module->firstUid($family) ?><?php endif ?>)</p>
            <?php else : ?>
                <?= I18N::translate('Private') ?></p>
            <?php endif ?>
        <?php endif ?>
    </caption>
    <tbody>
        <?php if (empty($family)) : ?>
            <!-- the individual itself -->
			<?php if (empty($with_css)) : ?>
			<tr class="text-center wt-family-navigator-parent">
			<?php else : ?>
            <tr class="text-center wt-family-navigator-parent wt-sex-<?= strtolower($individual->sex()) ?>">
			<?php endif ?>
                <?php if ($individual->canShow()) : ?>
                    <th class="align-middle mitalteli-show-xref-label" scope="row">
                         <?= $individual->xref() ?>
                            <i class="icon-selected"></i>
                    </th>
                    <td class="wt-family-navigator-name">
                        <?php if ($module->reallyCanShowName($individual)) : ?>
                            <?= $individual->fullName() ?>
                        <?php else : ?>
                            <?= I18N::translate('Private') ?>
                        <?php endif ?>
                        <?php if ($individual->canShow()) : ?>
                            <?php if ($with_uid) { $x = $module->firstUid($individual); if (!empty($x)) echo "<p class='uid'>$x</p>";}; ?>
                        <?php endif ?>
                    </td>
                <?php else : ?>
                    <th class="align-middle wt-family-navigator-label" scope="row">
                         <?= I18N::translate('Private') ?>
                    </th>
                    <td class="wt-family-navigator-name">
                         <?= I18N::translate('Private') ?>
                    </td>
                <?php endif ?>
            </tr>
        <?php else : ?>
            <?php foreach ($family->spouses() as $spouse) : ?>
				<?php if (empty($with_css)) : ?>
                <tr class="text-center wt-family-navigator-parent">
				<?php else : ?>
                <tr class="text-center wt-family-navigator-parent wt-sex-<?= strtolower($spouse->sex()) ?>">
				<?php endif ?>
                    <th class="align-middle mitalteli-show-xref-label" scope="row">
                        <?php if ($spouse === $individual) : ?>
                            <?= $spouse->xref() ?>
                            <i class="icon-selected"></i>
                        <?php elseif ($spouse->childFamilies()->isNotEmpty()) : ?>
                        <div class="dropdown">
                            <?php if ($spouse->canShow()) : ?>
                                <?= $spouse->xref() ?>
                                <a class="dropdown-toggle" href="#" role="button" id="dropdown-<?= e($spouse->xref()) ?>"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                </a>
                            <?php else : ?>
                                <?= I18N::translate('Private') ?>
                                <a class="dropdown-toggle" href="#" role="button" id="dropdown-<?= e(hash('sha256', $spouse->xref())) ?>"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                </a>
                            <?php endif ?>
    
                            <div class="dropdown-menu wt-family-navigator-dropdown">
                                <?php foreach ($spouse->childFamilies() as $n => $spouse_child_family) : ?>
                                    <?php if ($n > 0) : ?>
                                        <div class="dropdown-divider"></div>
                                    <?php endif ?>
                                    <div class="wt-family-navigator-dropdown-heading">
                                        <?= I18N::translate('Parents') ?>
                                        <?php if ($spouse_child_family->canShow()) : ?>
                                            <?php if ($with_link_symbol) : ?> <a href="<?= e($spouse_child_family->url()) ?>"><?= e($link_symbol ?? '⮺') ?></a><?php endif ?>
                                            <p class='uid'><?= $spouse_child_family->xref() ?>
                                            <?php if ($with_uid) : ?> <br /><?= $module->firstUid($spouse_child_family) ?><?php endif ?></p>
                                        <?php else : ?>
                                            <?= I18N::translate('Private') ?></p>
                                        <?php endif ?>
                                    </div>
                                    <?php foreach ($spouse_child_family->spouses() as $parent) : ?>
                                        <?php if ($module->reallyCanShowName($parent)) : ?>
                                            <?= $parent->fullName() ?>
                                        <?php else : ?>
                                            <?= I18N::translate('Private') ?>
                                        <?php endif ?>
                                        <?php if ($parent->canShow()) : ?>
                                            <?php if ($with_link_symbol) : ?> <a href="<?= e($parent->url()) ?>"><?= e($link_symbol ?? '⮺') ?></a><?php endif ?>
                                            <p class='uid'><?= $parent->xref() ?>
                                            <?php if ($with_uid) : ?> <br /><?= $module->firstUid($parent) ?><?php endif ?></p> <br />
                                        <?php else : ?>
                                            <?= I18N::translate('Private') ?></p> <br />
                                        <?php endif ?>
                                    <?php endforeach ?>
                                <?php endforeach ?>
                            </div>
                        </div>
                        <?php else : ?>
                            <?php if ($spouse->canShow()) : ?>
                                <?= $spouse->xref() ?>
                            <?php else : ?>
                                <?= I18N::translate('Private') ?>
                            <?php endif ?>
                        <?php endif ?>
                    </th>
    
                    <td class="wt-family-navigator-name">
                        <?php if ($module->reallyCanShowName($spouse)) : ?>
                            <?= $spouse->fullName() ?>
                        <?php else : ?>
                            <?= I18N::translate('Private') ?>
                        <?php endif ?>
                        <?php if ($spouse->canShow()) : ?>
                            <?php if ($with_link_symbol) : ?> <a href="<?= e($spouse->url()) ?>"><?= e($link_symbol ?? '⮺') ?></a><?php endif ?>
                            <?php if ($with_uid) { $x = $module->firstUid($spouse); if (!empty($x)) echo "<p class='uid'>$x</p>";}; ?>                        
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
    
            <?php foreach ($family->children() as $child) : ?>
				<?php if (empty($with_css)) : ?>
                <tr class="text-center wt-family-navigator-child">
				<?php else : ?>
                <tr class="text-center wt-family-navigator-child wt-sex-<?= strtolower($child->sex()) ?>">
				<?php endif ?>
                    <th class="align-middle mitalteli-show-xref-label" scope="row">
                        <?php if ($child === $individual) : ?>
                            <?php if ($child->canShow()) : ?>
                                <?= $child->xref() ?>
                            <?php else : ?>
                                <?= I18N::translate('Private') ?>
                            <?php endif ?>
                            <i class="icon-selected"></i>
                        <?php elseif ($child->spouseFamilies()->isNotEmpty()) : ?>
                            <div class="dropdown">
                                <?php if ($child->canShow()) : ?>
                                    <?= $child->xref() ?>
                                    <a class="dropdown-toggle" href="#" role="button" id="dropdown-<?= e($child->xref()) ?>"
                                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    </a>
                                <?php else : ?>
                                    <?= I18N::translate('Private') ?>
                                    <a class="dropdown-toggle" href="#" role="button" id="dropdown-<?= e(hash('sha256', $child->xref())) ?>"
                                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    </a>
                                <?php endif ?>

                                <div class="dropdown-menu">
                                    <?php foreach ($child->spouseFamilies() as $n => $in_laws) : ?>
                                        <?php if ($n > 0) : ?>
                                            <div class="dropdown-divider"></div>
                                        <?php endif ?>
                                        <div class="wt-family-navigator-dropdown-heading">
                                            <?php if ($in_laws->canShow()) : ?>
                                                <?= I18N::translate('Family') ?><?php if ($with_link_symbol) : ?> <a href="<?= e($in_laws->url()) ?>"><?= e($link_symbol ?? '⮺') ?></a><?php endif ?> <p class='uid'><?= $in_laws->xref() ?>
                                                <?php if ($with_uid) : ?> <br /><?= $module->firstUid($in_laws) ?><?php endif ?></p>
                                            <?php else : ?>
                                                <?= I18N::translate('Private') ?></p>
                                            <?php endif ?>
                                        </div>
    
                                        <?php foreach ($in_laws->spouses() as $sibling_in_law) : ?>
                                            <?php if ($sibling_in_law !== $child) : ?>
                                                <?php if ($module->reallyCanShowName($sibling_in_law)) : ?>
                                                    <?= $sibling_in_law->fullName() ?>
                                                <?php else : ?>
                                                    <?= I18N::translate('Private') ?>
                                                <?php endif ?>
                                                <?php if ($sibling_in_law->canShow()) : ?>
                                                    <?php if ($with_link_symbol) : ?> <a href="<?= e($sibling_in_law->url()) ?>"><?= e($link_symbol ?? '⮺') ?></a><?php endif ?> <p class='uid'><?= $sibling_in_law->xref() ?>
                                                    <?php if ($with_uid) : ?> <br /><?= $module->firstUid($sibling_in_law) ?><?php endif ?></p>
                                                <?php else : ?>
                                                    <?= I18N::translate('Private') ?></p>
                                                <?php endif ?>
                                            <?php endif ?>
                                        <?php endforeach ?>
    
                                        <ul>
                                            <?php foreach ($in_laws->children() as $child_in_law) : ?>
                                                <li>
                                                    <?php if ($module->reallyCanShowName($child_in_law)) : ?>
                                                        <?= $child_in_law->fullName() ?>
                                                    <?php else : ?>
                                                        <?= I18N::translate('Private') ?>
                                                    <?php endif ?>
                                                    <?php if ($child_in_law->canShow()) : ?>
                                                        <?php if ($with_link_symbol) : ?> <a href="<?= e($child_in_law->url()) ?>"><?= e($link_symbol ?? '⮺') ?></a><?php endif ?> <p class='uid'><?= $child_in_law->xref() ?>
                                                        <?php if ($with_uid) : ?> <br /><?= $module->firstUid($child_in_law) ?><?php endif ?></p>
                                                    <?php else : ?>
                                                        <?= I18N::translate('Private') ?></p>
                                                    <?php endif ?>
                                                </li>
                                            <?php endforeach ?>
                                        </ul>
                                    <?php endforeach ?>
                                </div>
                            </div>
                        <?php else : ?>
                            <?php if ($child !== $child) : ?>
                                <?= $child->xref() ?>
                            <?php else : ?>
                                <?= I18N::translate('Private') ?></p>
                            <?php endif ?>
                        <?php endif ?>
                    </th>
    
                    <td>
                        <?php if ($module->reallyCanShowName($child)) : ?>
                            <?= $child->fullName() ?>
                        <?php else : ?>
                            <?= I18N::translate('Private') ?>
                        <?php endif ?>
                        <?php if ($child->canShow()) : ?>
                            <?php if ($with_link_symbol) : ?> <a href="<?= e($child->url()) ?>"><?= e($link_symbol ?? '⮺') ?></a><?php endif ?>
                            <?php if ($with_uid) { $x = $module->firstUid($child); if (!empty($x)) echo "<p class='uid'>$x</p>";}; ?>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </tbody>
</table>
